name: tree
build: name:root
stages:
  - type: org.osbuild.kernel-cmdline
    options:
      root_fs_uuid: ${filesystems.raw.root.uuid}
      kernel_opts: ro no_timer_check console=ttyS0,115200n8 biosdevname=0 net.ifnames=0
  - otk.external.osbuild.depsolve-dnf4:
    architecture: ${architecture}
    module_platform_id: f${version}
    repositories: ${repositories}
    gpgkeys: ${gpgkeys}
    exclude:
      docs: true
    packages: ${packages.default.tree}
  - type: org.osbuild.fix-bls
    options:
      prefix: ''
  - otk.customization.locale:
    scope: tree  # XXX docs
    default:
      - type: org.osbuild.locale
        options:
          language: en_US
    defined:
      - type: org.osbuild.locale
        options:
          language: ${this.language}
  - otk.customization.hostname:
    scope: tree
    default:
      - type: org.osbuild.hostname
        options:
          hostname: localhost.localdomain
    defined:
      - type: org.osbuild.hostname
        options:
          hostname: ${this.hostname}
  - otk.customization.timezone:
    scope: tree
    default:
      - type: org.osbuild.timezone
        options:
          zone: UTC
    defined:
      - type: org.osbuild.timezone
        options:
          zone: ${this.timezone}
  - type: org.osbuild.fstab
    options: ${filesystems.raw}
  - type: org.osbuild.grub2
    options:
      root_fs_uuid: ${filesystems.raw.root.uuid}
      boot_fs_uuid: ${filesystems.raw.boot.uuid}
      kernel_opts: ro no_timer_check console=ttyS0,115200n8 biosdevname=0 net.ifnames=0
      legacy: i386-pc
      uefi:
        vendor: fedora
        unified: true
      saved_entry: "ffffffffffffffffffffffffffffffff-${packages.something.kernel-core.version}"
      write_cmdline: false
      config:
        default: saved
  - name: org.osbuild.selinux
    options:
      file_contexts: etc/selinux/targeted/contexts/files/file_contexts
